-- 1차 풀이
SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
FROM ANIMAL_OUTS
WHERE DATE_SUB(NOW(), INTERVAL 1 SECOND)
ORDER BY ANIMAL_OUTS.DATETIME DESC
LIMIT 2

-- 2차 풀이
SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
FROM ANIMAL_OUTS, ANIMAL_INS
WHERE ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
ORDER BY ANIMAL_OUTS.DATETIME - ANIMAL_INS.DATETIME
DESC LIMIT 2