--1차 풀이
SELECT (LEFT (DATETIME, 2)) AS 'HOUR', COUNT('HOUR') AS 'COUNT'
FROM ANIMAL_OUTS
WHERE 'HOUR' BETWEEN 09 AND 19
GROUP BY LEFT (DATETIME, 2);

--2차 풀이
SELECT HOUR(DATETIME) AS 'HOUR', COUNT(HOUR(DATETIME)) AS 'COUNT' 
FROM ANIMAL_OUTS 
WHERE HOUR(DATETIME) >= 9 AND HOUR(DATETIME) <= 19 
GROUP BY HOUR(DATETIME) 
ORDER BY HOUR(DATETIME)
